# This file defines the configuration for the tasks used in the one_crew_of_agents application.
#
# Each task is specified as a YAML key with the following fields:
#   - description:     A brief description of what the task does.
#   - expected_output: The expected result or output of the task.
#   - agent:           The agent responsible for executing the task.
#   - context:         (Optional) Other tasks whose outputs are required as input.
#   - output_file:     The file where the output will be saved.
#
# Tasks and their purpose:
#   - research_task: Conduct thorough research on a given topic.
#   - analysis_task: Analyze research findings and create a comprehensive report.
#   - send_email_task: Send an email with the report.
