# This file defines the configuration for the agents used in the three_engineering_team application.
#
# Each agent is specified as a YAML key with the following fields:
#   - role:        A brief description of the agent's function.
#   - goal:        The main objective the agent should accomplish.
#   - backstory:   Background information to provide context and expertise for the agent.
#   - llm:         The language model to be used for this agent.
#
# You can add new agents by following the same structure.
#
# Agents and their purpose:
#   - engineering_lead: Designs the backend module and provides detailed specifications for implementation.
#   - backend_engineer: Implements the backend module according to the engineering lead's design and requirements.
#   - frontend_engineer: Creates a Gradio UI to demonstrate the backend module's functionality.
#   - test_engineer: Writes unit tests to ensure the backend module works as intended.
