# This file defines the configuration for the tasks used in the three_engineering_team application.
#
# Each task is specified as a YAML key with the following fields:
#   - description:     A brief description of what the task does.
#   - expected_output: The expected result or output of the task.
#   - agent:           The agent responsible for executing the task.
#   - context:         (Optional) Other tasks whose outputs are required as input.
#   - output_file:     The file where the output will be saved.
#
# Tasks and their purpose:
#   - design_task: Prepares a detailed design for the backend module based on requirements.
#   - test_task: Writes unit tests for the backend module using the design.
#   - code_task: Implements the backend module according to the design and tests.
#   - frontend_task: Creates a Gradio UI to demonstrate the backend module's functionality.
